### ISSUE TITLE
Discussion about tests

### ISSUE THREAD

**Issue by arwer13** [epogrebnyak/make-xls-model#25]
#### First impressions
1. I believe all tests should be in one folder
2. It seams for me tests could be separated in two groups:
   - tests for functions saving and loading to/from xls. These tests should be accompanied by xls files
   - tests for functions internally manipulating data. There should be no xls files for these tests.
3. Should something be done with make_xls_model_test/temp.py now?

**Comment by epogrebnyak** [comment]
Update:
1.  tests cannot be in separate folder unless we have a package and for simplicity we don't -> all tests are now in code root
2. groups of tests:
- (a) input: reading from excel file 
- (b) operations on data  
- (c) output: writing to xl files

3  temp.py moved to issues fodler as a demo for using xlrd and other libraries

For practical reasons (a)+(b) is one group of test (implemented in commits below), (c) is separate group of tests, not implemented yet. Can also do (a) separately, but it is too costly to do (b) separately (too many constants/fixtures).

**Comment by epogrebnyak** [comment]
Also addressed in #34

**Comment by epogrebnyak** [comment]
@arwer13 After completing #34 we shall have a minimal 'suite' for testing. 

What other extensions can there be to tests (not for immediate implementation)? 

What comes to my mind is:
- there are doctest tests in some individual files that we do not invoke
- examples.bat can be a test  
- testiong ability to write and read from Excel files
- what else?

**Comment by arwer13** [comment]
> testing ability to write and read from Excel files

Aren't `(a)` and `(b)` about it?

> examples.bat can be a test

I still can't get the purpose of examples.bat. For whom it is? If for users, than it doesn't seem for me to be good place for invoking tests. If it's for developers, I would prefer just script for running all (unit) tests.

> there are doctest tests in some individual files that we do not invoke
1. I would like to have one .bat file to run all tests we have. I may invoke examples.bat just to check they doesn't fail
2. Why not to switch to one testing framework? And if one asks me I would choose py.test, because I don't like doc tests, and see not much sense if they are not used for documentation generation. But anyway it's just an opinion, I understand there were some reasons for this.
